artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/Spencer0013/NLP-Text-Summarizer-Project/raw/refs/heads/main/Dataa.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_preprocessing:
  root_dir: artifacts/data_preprocessing
  ingestion_dir: artifacts/data_ingestion
  output_dir: artifacts/data_preprocessing



data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_preprocessing
  

model_trainer:
  root_dir: artifacts/model_trainer
  data_path: artifacts/data_transformation
  model_save_path: artifacts/model_trainer/sentiment_model



  






  